# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 747b3f82da54e02ae465af801c3af0cd2c2a217df613e5acecd9419000136cfc6d1a3e7c2a990293005868d6c37ccdf8a5371edc6fe64b7fc1b8a0253d6a6929

test:
  secret_key_base: 65813be35135502dbd78bfa88f8737a62d0f732910135bf9a575fc7a026f1095959b047cd0eb6bb541cb6522df4b4c5d435a717cdbf28ea4be94920e39cdeea2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
